// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-branches.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_branches_default = defineTool({
  name: "list_branches",
  title: "List branches",
  description: "List the active branches the signed-in user can access in their organization. Returns id, name, location, phone, and whatsapp_chat_id.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("branches").select("id,name,location,phone,whatsapp_chat_id,is_active").eq("is_deleted", false).eq("is_active", true).order("name");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { branches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/revenue-summary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var revenue_summary_default = defineTool2({
  name: "revenue_summary",
  title: "Revenue summary",
  description: "Summarize confirmed revenue between two dates (inclusive, YYYY-MM-DD) for the signed-in user's organization. Optionally filter by branch_id. Returns total_amount (SDG), confirmed_count, rejected_count.",
  inputSchema: {
    from_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Start date, YYYY-MM-DD"),
    to_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("End date, YYYY-MM-DD"),
    branch_id: z.string().uuid().optional().describe("Optional branch UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, branch_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("transfers").select("amount,is_confirmed,needs_review,fraud_score", { count: "exact" }).eq("is_deleted", false).gte("transfer_date", from_date).lte("transfer_date", to_date);
    if (branch_id) q = q.eq("branch_id", branch_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const total_amount = rows.filter((r) => r.is_confirmed).reduce((s, r) => s + Number(r.amount || 0), 0);
    const confirmed_count = rows.filter((r) => r.is_confirmed).length;
    const rejected_count = rows.filter(
      (r) => (r.fraud_score ?? 0) > 0 || r.needs_review
    ).length;
    const summary = {
      from_date,
      to_date,
      branch_id: branch_id ?? null,
      total_amount,
      currency: "SDG",
      confirmed_count,
      rejected_count
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-recent-transfers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_transfers_default = defineTool3({
  name: "list_recent_transfers",
  title: "List recent transfers",
  description: "List the most recent bank transfers for the signed-in user's organization. Optional branch_id filter and limit (1-50, default 10).",
  inputSchema: {
    branch_id: z2.string().uuid().optional(),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ branch_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("transfers").select(
      "id,branch_id,amount,transfer_date,sender_name,is_confirmed,needs_review,client_memo,created_at"
    ).eq("is_deleted", false).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (branch_id) q = q.eq("branch_id", branch_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transfers: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vqfkggdvqfcvakuypkty";
var mcp_default = defineMcp({
  name: "hesabaty-mcp",
  title: "Hesabaty PRO",
  version: "0.1.0",
  instructions: "Tools for Hesabaty PRO. Read the signed-in user's branches, recent bank transfers, and confirmed revenue summaries. All calls run under the user's Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_branches_default, revenue_summary_default, list_recent_transfers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
